Check the required variables before starting

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -33,10 +33,19 @@ jobs:
       # ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/${{ env.NDK_VERSION }}
       # ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/${{ env.NDK_VERSION }}
       # ORG_GRADLE_PROJECT_android_ndkPath: /usr/local/lib/android/sdk/ndk/${{ env.NDK_VERSION }}
-      GPR_USER: ${{ vars.GPR_USER }}
-      GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
 
     steps:
+      - name: Check variables
+        run: |
+          if [ -z "${{ env.HERE_SDK_AAR_NAME }}" ]; then
+            echo "HERE SDK artifact name not found in gradle.properties"
+            exit 1
+          fi
+          if [ -z "${{ vars.GPR_USER }}" ] || [ -z "${{ secrets.GPR_TOKEN }}" ]; then
+            echo "GPR credentials are not available"
+            exit 1
+          fi
+
       - name: Checkout
         uses: actions/checkout@v4
 
@@ -112,22 +121,20 @@ jobs:
         if: steps.detect.outputs.changed_modules != ''
         env:
           HERE_SDK_AAR_NAME: ${{ steps.define.outputs.here_sdk_artifact }}
-          GPR_USER: ${{ vars.GPR_USER }}
-          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
         run: |
-          if [ -z "${{ env.HERE_SDK_AAR_NAME }}" ]; then
-            echo "HERE SDK artifact name not found in gradle.properties"
-            exit 1
-          fi
-          if [ -z "${{ env.GPR_USER }}" ] || [ -z "${{ env.GPR_TOKEN }}" ]; then
-            echo "GPR credentials are not available"
-            exit 1
-          fi
+#          if [ -z "${{ env.HERE_SDK_AAR_NAME }}" ]; then
+#            echo "HERE SDK artifact name not found in gradle.properties"
+#            exit 1
+#          fi
+#          if [ -z "${{ vars.GPR_USER }}" ] || [ -z "${{ secrets.GPR_TOKEN }}" ]; then
+#            echo "GPR credentials are not available"
+#            exit 1
+#          fi
           mkdir -p libs
           target_path="libs/${HERE_SDK_AAR_NAME}.aar"
           echo "Downloading HERE SDK mock artifact to $target_path"
           curl --fail --show-error --silent --location \
-            -u "${{ env.GPR_USER }}:${{ env.GPR_TOKEN }}" \
+            -u "${{ vars.GPR_USER }}:${{ secrets.GPR_TOKEN }}" \
             -o "$target_path" \
             "https://raw.githubusercontent.com/MapConductor/here-sdk-mocks/main/heresdk-explore-mock-4.23.2.0.210004.jar"
           if [ ! -s "$target_path" ]; then
